# Generated by Django 5.2.17 on 2026-09-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_liter', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_milk_productions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeatProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_gain_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meat_productions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('period', models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], max_length=10, null=True)),
                ('liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_liter', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('feeding_type', models.CharField(blank=True, max_length=191, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'milk_productions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MilkUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('calf_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consumed_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'milk_usages',
                'managed': False,
            },
        ),
    ]
