# Generated by Django 5.2.17 on 2026-09-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=191)),
                ('last_name', models.CharField(max_length=191)),
                ('document_type', models.CharField(max_length=191)),
                ('name', models.CharField(blank=True, max_length=191, null=True)),
                ('document', models.CharField(max_length=191, unique=True)),
                ('phone', models.CharField(blank=True, max_length=191, null=True)),
                ('email', models.CharField(max_length=191, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=191)),
                ('role', models.CharField(default='user', max_length=40)),
                ('admin_permissions', models.JSONField(blank=True, null=True)),
                ('subscription_plan_id', models.BigIntegerField(blank=True, null=True)),
                ('billing_status', models.CharField(default='trial', max_length=40)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('has_completed_onboarding', models.BooleanField(default=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_farm_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
