# Generated by Django 5.2.17 on 2026-09-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('subscription_plan_id', models.BigIntegerField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=191, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='COP', max_length=10)),
                ('billing_period', models.CharField(blank=True, max_length=30, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan_id', models.BigIntegerField(blank=True, null=True)),
                ('subscription_invoice_id', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='COP', max_length=10)),
                ('billing_period', models.CharField(blank=True, max_length=30, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='paid', max_length=30)),
                ('payment_method', models.CharField(blank=True, max_length=191, null=True)),
                ('provider', models.CharField(blank=True, max_length=191, null=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=191, null=True)),
                ('provider_status', models.CharField(blank=True, max_length=191, null=True)),
                ('reference', models.CharField(blank=True, max_length=191, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('provider_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='wompi', max_length=191)),
                ('provider_token', models.CharField(blank=True, max_length=191, null=True)),
                ('holder_name', models.CharField(blank=True, max_length=191, null=True)),
                ('brand', models.CharField(blank=True, max_length=191, null=True)),
                ('last_four', models.CharField(max_length=4)),
                ('expiry_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expiry_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=30)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_payment_methods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('slug', models.CharField(max_length=191, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('billing_period', models.CharField(default='monthly', max_length=30)),
                ('max_farms', models.PositiveIntegerField(blank=True, null=True)),
                ('max_users', models.PositiveIntegerField(blank=True, null=True)),
                ('max_animals', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'managed': False,
            },
        ),
    ]
