# Generated by Django 5.2.17 on 2026-09-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('code', models.CharField(blank=True, max_length=191, null=True)),
                ('type', models.CharField(blank=True, max_length=191, null=True)),
                ('status', models.CharField(default='activo', max_length=191)),
                ('area_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area_calculated', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('polygon', models.JSONField(blank=True, null=True)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('center_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lots',
                'managed': False,
            },
        ),
    ]
