# Generated by Django 5.2.17 on 2026-09-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso')], max_length=10)),
                ('title', models.CharField(max_length=191)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('milk_liters_sold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('milk_price_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('milk_sale_start_date', models.DateField(blank=True, null=True)),
                ('milk_sale_end_date', models.DateField(blank=True, null=True)),
                ('transaction_date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=191, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=191, null=True)),
                ('reference', models.CharField(blank=True, max_length=191, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financial_transactions',
                'managed': False,
            },
        ),
    ]
