# Generated by Django 5.2.17 on 2026-09-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('internal_code', models.CharField(blank=True, max_length=191, null=True)),
                ('ear_tag', models.CharField(blank=True, max_length=191, null=True)),
                ('name', models.CharField(blank=True, max_length=191, null=True)),
                ('species', models.CharField(default='bovino', max_length=191)),
                ('breed', models.CharField(blank=True, max_length=191, null=True)),
                ('sex', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=191, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('carne', 'Carne'), ('leche', 'Leche'), ('doble_proposito', 'Doble propósito'), ('crianza', 'Crianza')], max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('dam_name_manual', models.CharField(blank=True, max_length=191, null=True)),
                ('sire_name_manual', models.CharField(blank=True, max_length=191, null=True)),
                ('has_calved_before', models.CharField(blank=True, max_length=191, null=True)),
                ('is_pregnant', models.CharField(blank=True, max_length=191, null=True)),
                ('pregnancy_date', models.DateField(blank=True, null=True)),
                ('pregnancy_sire_name_manual', models.CharField(blank=True, max_length=191, null=True)),
                ('service_type', models.CharField(blank=True, max_length=30, null=True)),
                ('last_calving_date', models.DateField(blank=True, null=True)),
                ('dry_off_date', models.DateField(blank=True, null=True)),
                ('calving_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_birth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weight_current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('last_weight_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='activo', max_length=191)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('status_notes', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=191, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalLotHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.BigIntegerField(blank=True, null=True)),
                ('lot_id', models.BigIntegerField()),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animal_lot_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=191)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animal_photos',
                'managed': False,
            },
        ),
    ]
