# Generated by Django 5.2.17 on 2026-09-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, max_length=80, null=True)),
                ('source_key', models.CharField(blank=True, max_length=120, null=True)),
                ('level', models.CharField(default='medium', max_length=30)),
                ('title', models.CharField(max_length=191)),
                ('message', models.TextField()),
                ('event_date', models.DateField(blank=True, null=True)),
                ('lot_name', models.CharField(blank=True, max_length=191, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'farm_notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('endpoint_hash', models.CharField(max_length=64, unique=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('auth_token', models.TextField(blank=True, null=True)),
                ('content_encoding', models.CharField(blank=True, max_length=32, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'web_push_subscriptions',
                'managed': False,
            },
        ),
    ]
